version: '2'
command: RUN chmod 777 -R /var/www/html
services:
  web:
    depends_on:
      - api
    build: ./easytourWeb
    ports:
      - "8000:80"
    volumes:
      - ./easytourWeb:/var/www/html
  api:
    depends_on:
      - db_api
    build: ./easytourApi
    ports:
      - "8001:80"
    volumes:
      - "./easytourApi:/var/www/html"
    links:
      - db_api

  db_api:
    image: postgres:9.6
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: easytourbrasil
      LC_ALL: C
