version: '2'
services:
  web:
    build: ./easyTourWEB
    ports:
      - "8000:80"
  api:
    depends_on:
      - db_api
    build: ./easyTourAPI
    ports:
      - "8001:80"
    links:
      - db_api

  db_api:
    image: postgres:9.6
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: easytourbrasil
      LC_ALL: C
