version: '2'
services:
  web:
    depends_on:
      - api
    build: ./easytourWeb
    networks:
      mynet:
        ipv4_address: 172.25.0.4
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
  api:
    depends_on:
      - db_api
    build: ./easytourApi
    networks:
      mynet:
        ipv4_address: 172.25.0.2
    ports:
      - "8001:80"
    volumes:
      - "./:/var/www/html"
    links:
      - db_api

  db_api:
    image: postgres:9.6
    networks:
      mynet:
        ipv4_address: 172.25.0.3
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: easytourbrasil
      LC_ALL: C

networks:
  mynet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
